[package]
name = "ontologos-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Query interface for Ontologos ontologies"
publish = false

[dependencies]
ontologos-core = { workspace = true }
thiserror = { workspace = true }
