[package]
name = "ontologos-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Query interface for OntoLogos ontologies"
publish = true


[lints]
workspace = true

[dependencies]
ontologos-core = { workspace = true }
ontologos-ql = { workspace = true }
thiserror = { workspace = true }
