[package]
name = "ontologos-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Deprecated re-export of taxonomy hierarchy in ontologos-ql"
publish = true


[lints]
workspace = true

[dependencies]
ontologos-ql = { workspace = true }
