[package]
name = "ontologos-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Python bindings for OntoLogos"
publish = false

[lib]
name = "_ontologos"
crate-type = ["cdylib"]

[dependencies]
ontologos-core = { workspace = true }
ontologos-parser = { workspace = true }
ontologos-rdfs = { workspace = true }
ontologos-rl = { workspace = true }
ontologos-el = { workspace = true }
ontologos-facade = { workspace = true }
ontologos-dl = { workspace = true }
ontologos-explain = { workspace = true }
serde_json = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py310", "generate-import-lib"] }

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]
