/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the OntoLogos error code prefix from a Node error message, if present. */
export declare function errorCodeFromMessage(message: string): string | null
/** Package version string. */
export declare function version(): string
/** Entailment check input (exactly one axiom shape). */
export interface EntailmentCheck {
  sub?: string
  sup?: string
  individual?: string
  class?: string
  subject?: string
  property?: string
  object?: string
}
/** In-memory ontology. */
export declare class Ontology {
  static fromJson(json: string): Ontology
  static fromJsonWithLimits(json: string, maxJsonBytes?: number | undefined | null, maxEntities?: number | undefined | null, maxAxioms?: number | undefined | null, maxIriLen?: number | undefined | null): Ontology
  static fromObject(value: any): Ontology
  static fromObjectWithLimits(value: any, maxJsonBytes?: number | undefined | null, maxEntities?: number | undefined | null, maxAxioms?: number | undefined | null, maxIriLen?: number | undefined | null): Ontology
  static fromBytes(bytes: Buffer): Ontology
  static fromBytesLenient(bytes: Buffer): Ontology
  static fromText(text: string): Ontology
  static fromTextLenient(text: string): Ontology
  /** Load from a trusted local path (strict parse by default). */
  static load(path: string, lenient?: boolean | undefined | null): Ontology
  /** Sandboxed load constrained to `base` (strict parse by default). */
  static loadIn(base: string, path: string, lenient?: boolean | undefined | null): Ontology
  toJson(): string
  toObject(): any
  get axiomCount(): number
  get entityCount(): number
}
export type JsOntologyBuilderWrap = OntologyBuilder
/** Fluent builder for constructing ontologies. */
export declare class OntologyBuilder {
  constructor()
  addClass(iri: string): void
  individual(iri: string): void
  objectProperty(iri: string): void
  subclassOf(subclass: string, superclass: string): void
  subpropertyOf(sub: string, sup: string): void
  propertyDomain(property: string, domain: string): void
  propertyRange(property: string, range: string): void
  classAssertion(individual: string, class: string): void
  objectPropertyAssertion(subject: string, property: string, object: string): void
  build(): Ontology
}
/** OWL reasoner. */
export declare class Reasoner {
  constructor(ontology: Ontology, profile?: string | undefined | null, incremental?: boolean | undefined | null, budgetSecs?: number | undefined | null)
  static fromPath(path: string, profile?: string | undefined | null, incremental?: boolean | undefined | null, budgetSecs?: number | undefined | null, lenient?: boolean | undefined | null): Reasoner
  static loadIn(base: string, path: string, profile?: string | undefined | null, incremental?: boolean | undefined | null, budgetSecs?: number | undefined | null, lenient?: boolean | undefined | null): Reasoner
  get parseMeta(): any
  get taxonomy(): any | null
  classify(): any
  explain(): any
  checkConsistency(): any
  isConsistent(): boolean
  isEntailed(check: EntailmentCheck): boolean
  query(query: string): Array<any>
  addSubclassOf(subclass: string, superclass: string): void
  removeSubclassOf(subclass: string, superclass: string): void
  addAxiomJson(axiom: any): void
}
