[package]
name = "ontologos-el"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "OWL EL classification engine for OntoLogos"
publish = true


[lints]
workspace = true

[dependencies]
ontologos-core = { workspace = true }
ontologos-profile = { workspace = true }
ontologos-rl = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ontologos-parser = { workspace = true }
criterion = "0.5"

[[bench]]
name = "classify"
harness = false
