[package]
name = "ontologos-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core data model and reasoner API for OntoLogos"
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = false

[[example]]
name = "pizza_builder"
path = "examples/pizza_builder.rs"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
ontologos-parser = { workspace = true }
ontologos-profile = { workspace = true }

[[bench]]
name = "serialize_bench"
harness = false
