// Auto-generated by tests/hermit/generate_catalog.py — do not edit.

use ontologos_conformance::run_hermit_case;

#[test]
fn hermit_reasoner_anyuritest_testlength_1() {
    run_hermit_case("reasoner.AnyURITest.testLength_1");
}

#[test]
fn hermit_reasoner_anyuritest_testlength_2() {
    run_hermit_case("reasoner.AnyURITest.testLength_2");
}

#[test]
fn hermit_reasoner_anyuritest_testlength_3() {
    run_hermit_case("reasoner.AnyURITest.testLength_3");
}

#[test]
fn hermit_reasoner_anyuritest_testlength_4() {
    run_hermit_case("reasoner.AnyURITest.testLength_4");
}

#[test]
fn hermit_reasoner_anyuritest_testlength_5() {
    run_hermit_case("reasoner.AnyURITest.testLength_5");
}

#[test]
fn hermit_reasoner_anyuritest_testsize_1() {
    run_hermit_case("reasoner.AnyURITest.testSize_1");
}

#[test]
fn hermit_reasoner_anyuritest_testsize_2() {
    run_hermit_case("reasoner.AnyURITest.testSize_2");
}

#[test]
fn hermit_reasoner_anyuritest_testsize_3() {
    run_hermit_case("reasoner.AnyURITest.testSize_3");
}

#[test]
fn hermit_reasoner_anyuritest_testintersection() {
    run_hermit_case("reasoner.AnyURITest.testIntersection");
}

#[test]
fn hermit_reasoner_anyuritest_testpattern1_1() {
    run_hermit_case("reasoner.AnyURITest.testPattern1_1");
}

#[test]
fn hermit_reasoner_anyuritest_testpattern1_2() {
    run_hermit_case("reasoner.AnyURITest.testPattern1_2");
}

#[test]
fn hermit_reasoner_anyuritest_testpattern2_1() {
    run_hermit_case("reasoner.AnyURITest.testPattern2_1");
}

#[test]
fn hermit_reasoner_anyuritest_testpattern2_2() {
    run_hermit_case("reasoner.AnyURITest.testPattern2_2");
}

#[test]
fn hermit_reasoner_anyuritest_testpattern3() {
    run_hermit_case("reasoner.AnyURITest.testPattern3");
}

#[test]
fn hermit_reasoner_anyuritest_testpatternandlength1_1() {
    run_hermit_case("reasoner.AnyURITest.testPatternAndLength1_1");
}

#[test]
fn hermit_reasoner_anyuritest_testpatternandlength1_2() {
    run_hermit_case("reasoner.AnyURITest.testPatternAndLength1_2");
}

#[test]
fn hermit_reasoner_anyuritest_testpatternandlength1_3() {
    run_hermit_case("reasoner.AnyURITest.testPatternAndLength1_3");
}

#[test]
fn hermit_reasoner_anyuritest_testpatterncomplement1_1() {
    run_hermit_case("reasoner.AnyURITest.testPatternComplement1_1");
}

#[test]
fn hermit_reasoner_anyuritest_testpatterncomplement1_2() {
    run_hermit_case("reasoner.AnyURITest.testPatternComplement1_2");
}

#[test]
fn hermit_reasoner_anyuritest_testpatterncomplement1_3() {
    run_hermit_case("reasoner.AnyURITest.testPatternComplement1_3");
}

#[test]
fn hermit_reasoner_binarydatatest_testparsing_1() {
    run_hermit_case("reasoner.BinaryDataTest.testParsing_1");
}

#[test]
fn hermit_reasoner_binarydatatest_testparsing_2() {
    run_hermit_case("reasoner.BinaryDataTest.testParsing_2");
}

#[test]
fn hermit_reasoner_binarydatatest_testlength_1() {
    run_hermit_case("reasoner.BinaryDataTest.testLength_1");
}

#[test]
fn hermit_reasoner_binarydatatest_testlength_2() {
    run_hermit_case("reasoner.BinaryDataTest.testLength_2");
}

#[test]
fn hermit_reasoner_binarydatatest_testlength_3() {
    run_hermit_case("reasoner.BinaryDataTest.testLength_3");
}

#[test]
fn hermit_reasoner_binarydatatest_testlength_4() {
    run_hermit_case("reasoner.BinaryDataTest.testLength_4");
}

#[test]
fn hermit_reasoner_binarydatatest_testlength_5() {
    run_hermit_case("reasoner.BinaryDataTest.testLength_5");
}

#[test]
fn hermit_reasoner_binarydatatest_testsize_1() {
    run_hermit_case("reasoner.BinaryDataTest.testSize_1");
}

#[test]
fn hermit_reasoner_binarydatatest_testsize_2() {
    run_hermit_case("reasoner.BinaryDataTest.testSize_2");
}

#[test]
fn hermit_reasoner_binarydatatest_testsize_3() {
    run_hermit_case("reasoner.BinaryDataTest.testSize_3");
}

#[test]
fn hermit_reasoner_binarydatatest_testintersection_1() {
    run_hermit_case("reasoner.BinaryDataTest.testIntersection_1");
}

#[test]
fn hermit_reasoner_binarydatatest_testintersection_2() {
    run_hermit_case("reasoner.BinaryDataTest.testIntersection_2");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithdatatypes() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithDatatypes");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithdatatypes2() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithDatatypes2");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithnominals() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithNominals");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithnominals2() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithNominals2");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithnominals3() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithNominals3");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithnominals4() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithNominals4");
}

#[test]
fn hermit_reasoner_complexconcepttest_testconceptwithnominals5() {
    run_hermit_case("reasoner.ComplexConceptTest.testConceptWithNominals5");
}

#[test]
fn hermit_reasoner_complexconcepttest_testjustifications() {
    run_hermit_case("reasoner.ComplexConceptTest.testJustifications");
}

#[test]
fn hermit_reasoner_datalogenginetest_testbasic() {
    run_hermit_case("reasoner.DatalogEngineTest.testBasic");
}

#[test]
fn hermit_reasoner_datalogenginetest_testequality() {
    run_hermit_case("reasoner.DatalogEngineTest.testEquality");
}

#[test]
fn hermit_reasoner_datalogenginetest_testquerywithindividualsandequality() {
    run_hermit_case("reasoner.DatalogEngineTest.testQueryWithIndividualsAndEquality");
}

#[test]
fn hermit_reasoner_datalogenginetest_testquerywithindividuals() {
    run_hermit_case("reasoner.DatalogEngineTest.testQueryWithIndividuals");
}

#[test]
fn hermit_reasoner_datatypestest_testnotxsdstring() {
    run_hermit_case("reasoner.DatatypesTest.testNotXsdString");
}

#[test]
fn hermit_reasoner_datatypestest_testdatetimetimezones() {
    run_hermit_case("reasoner.DatatypesTest.testdateTimeTimezones");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef5() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef5");
}

#[test]
fn hermit_reasoner_datatypestest_testnominalsanddatatypesfromalan() {
    run_hermit_case("reasoner.DatatypesTest.testNominalsAndDatatypesFromAlan");
}

#[test]
fn hermit_reasoner_datatypestest_testdifferentlexicalforms() {
    run_hermit_case("reasoner.DatatypesTest.testDifferentLexicalForms");
}

#[test]
fn hermit_reasoner_datatypestest_testliteralcustomdatatype() {
    run_hermit_case("reasoner.DatatypesTest.testLiteralCustomDatatype");
}

#[test]
fn hermit_reasoner_datatypestest_testinf() {
    run_hermit_case("reasoner.DatatypesTest.testINF");
}

#[test]
fn hermit_reasoner_datatypestest_testfreshentitiesquery() {
    run_hermit_case("reasoner.DatatypesTest.testFreshEntitiesQuery");
}

#[test]
fn hermit_reasoner_datatypestest_testparsingerror() {
    run_hermit_case("reasoner.DatatypesTest.testParsingError");
}

#[test]
fn hermit_reasoner_datatypestest_teststringabbreviation() {
    run_hermit_case("reasoner.DatatypesTest.testStringAbbreviation");
}

#[test]
fn hermit_reasoner_datatypestest_testlangabbreviation() {
    run_hermit_case("reasoner.DatatypesTest.testLangAbbreviation");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypesunsat1() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypesUnsat1");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypesunsat2() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypesUnsat2");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypesunsat3() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypesUnsat3");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypesunsat4() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypesUnsat4");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypessat() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypesSat");
}

#[test]
fn hermit_reasoner_datatypestest_testmininclusivemaxinclusive() {
    run_hermit_case("reasoner.DatatypesTest.testMinInclusiveMaxInclusive");
}

#[test]
fn hermit_reasoner_datatypestest_testdisjointdpsunsat() {
    run_hermit_case("reasoner.DatatypesTest.testDisjointDPsUnsat");
}

#[test]
fn hermit_reasoner_datatypestest_testdisjointdpsunsatstrings() {
    run_hermit_case("reasoner.DatatypesTest.testDisjointDPsUnsatStrings");
}

#[test]
fn hermit_reasoner_datatypestest_testdisjointdpssatinteger() {
    run_hermit_case("reasoner.DatatypesTest.testDisjointDPsSatInteger");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfrominteger1() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromInteger1");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfrominteger2() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromInteger2");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfrommixed1() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromMixed1");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfrommixed2() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromMixed2");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfromdifferenttypes1() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromDifferentTypes1");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfromdifferenttypes2() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromDifferentTypes2");
}

#[test]
fn hermit_reasoner_datatypestest_testallvaluesfromdifferenttypes3() {
    run_hermit_case("reasoner.DatatypesTest.testAllValuesFromDifferentTypes3");
}

#[test]
fn hermit_reasoner_datatypestest_testnegzero1integer() {
    run_hermit_case("reasoner.DatatypesTest.testNegZero1Integer");
}

#[test]
fn hermit_reasoner_datatypestest_testnegzero2integer() {
    run_hermit_case("reasoner.DatatypesTest.testNegZero2Integer");
}

#[test]
fn hermit_reasoner_datatypestest_testintplusdecimal() {
    run_hermit_case("reasoner.DatatypesTest.testIntPlusDecimal");
}

#[test]
fn hermit_reasoner_datatypestest_testintplusdecimal2() {
    run_hermit_case("reasoner.DatatypesTest.testIntPlusDecimal2");
}

#[test]
fn hermit_reasoner_datatypestest_testdecimals() {
    run_hermit_case("reasoner.DatatypesTest.testDecimals");
}

#[test]
fn hermit_reasoner_datatypestest_testdecimalplusowlreal() {
    run_hermit_case("reasoner.DatatypesTest.testDecimalPlusOWLreal");
}

#[test]
fn hermit_reasoner_datatypestest_testdecimalplusinteger() {
    run_hermit_case("reasoner.DatatypesTest.testDecimalPlusInteger");
}

#[test]
fn hermit_reasoner_datatypestest_testdifferentoneofs() {
    run_hermit_case("reasoner.DatatypesTest.testDifferentOneOfs");
}

#[test]
fn hermit_reasoner_datatypestest_testfloatzeros() {
    run_hermit_case("reasoner.DatatypesTest.testFloatZeros");
}

#[test]
fn hermit_reasoner_datatypestest_testfloatenuminconsistent() {
    run_hermit_case("reasoner.DatatypesTest.testFloatEnumInconsistent");
}

#[test]
fn hermit_reasoner_datatypestest_testrationals1() {
    run_hermit_case("reasoner.DatatypesTest.testRationals1");
}

#[test]
fn hermit_reasoner_datatypestest_testrationals2() {
    run_hermit_case("reasoner.DatatypesTest.testRationals2");
}

#[test]
fn hermit_reasoner_datatypestest_testrationals3() {
    run_hermit_case("reasoner.DatatypesTest.testRationals3");
}

#[test]
fn hermit_reasoner_datatypestest_testdatetime1() {
    run_hermit_case("reasoner.DatatypesTest.testDateTime1");
}

#[test]
fn hermit_reasoner_datatypestest_testdatetime2() {
    run_hermit_case("reasoner.DatatypesTest.testDateTime2");
}

#[test]
fn hermit_reasoner_datatypestest_testselfinequality() {
    run_hermit_case("reasoner.DatatypesTest.testSelfInequality");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef1() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef1");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef2() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef2");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef3() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef3");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef4() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef4");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypedef6() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeDef6");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunion1() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnion1");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunion2() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnion2");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunion3() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnion3");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunion4() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnion4");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunionintersection1() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnionIntersection1");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunionintersection2() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnionIntersection2");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunionintersection3() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnionIntersection3");
}

#[test]
fn hermit_reasoner_datatypestest_testdatatypeunionintersection4() {
    run_hermit_case("reasoner.DatatypesTest.testDatatypeUnionIntersection4");
}

#[test]
fn hermit_reasoner_datatypestest_testnegativedpassertions() {
    run_hermit_case("reasoner.DatatypesTest.testNegativeDPAssertions");
}

#[test]
fn hermit_reasoner_datetimetest_testfinite1_1() {
    run_hermit_case("reasoner.DateTimeTest.testFinite1_1");
}

#[test]
fn hermit_reasoner_datetimetest_testfinite1_2() {
    run_hermit_case("reasoner.DateTimeTest.testFinite1_2");
}

#[test]
fn hermit_reasoner_datetimetest_testfinite2_1() {
    run_hermit_case("reasoner.DateTimeTest.testFinite2_1");
}

#[test]
fn hermit_reasoner_datetimetest_testfinite2_2() {
    run_hermit_case("reasoner.DateTimeTest.testFinite2_2");
}

#[test]
fn hermit_reasoner_datetimetest_testinfinite_1() {
    run_hermit_case("reasoner.DateTimeTest.testInfinite_1");
}

#[test]
fn hermit_reasoner_datetimetest_testinfinite_2() {
    run_hermit_case("reasoner.DateTimeTest.testInfinite_2");
}

#[test]
fn hermit_reasoner_datetimetest_testmizedtzs_1() {
    run_hermit_case("reasoner.DateTimeTest.testMizedTZs_1");
}

#[test]
fn hermit_reasoner_datetimetest_testmizedtzs_2() {
    run_hermit_case("reasoner.DateTimeTest.testMizedTZs_2");
}

#[test]
fn hermit_reasoner_datetimetest_testmizedtzs_3() {
    run_hermit_case("reasoner.DateTimeTest.testMizedTZs_3");
}

#[test]
fn hermit_reasoner_datetimetest_testmember() {
    run_hermit_case("reasoner.DateTimeTest.testMember");
}

#[test]
fn hermit_reasoner_entailmenttest_testhaskey() {
    run_hermit_case("reasoner.EntailmentTest.testHasKey");
}

#[test]
fn hermit_reasoner_entailmenttest_testblanknodes1() {
    run_hermit_case("reasoner.EntailmentTest.testBlankNodes1");
}

#[test]
fn hermit_reasoner_entailmenttest_testinvalidblanknodes() {
    run_hermit_case("reasoner.EntailmentTest.testInvalidBlankNodes");
}

#[test]
fn hermit_reasoner_entailmenttest_testvalidblanknodeswithnominals() {
    run_hermit_case("reasoner.EntailmentTest.testValidBlankNodesWithNominals");
}

#[test]
fn hermit_reasoner_entailmenttest_testvalidblanknodesinpremise() {
    run_hermit_case("reasoner.EntailmentTest.testValidBlankNodesInPremise");
}

#[test]
fn hermit_reasoner_entailmenttest_testvalidblanknodes() {
    run_hermit_case("reasoner.EntailmentTest.testValidBlankNodes");
}

#[test]
fn hermit_reasoner_entailmenttest_testblankwithdts() {
    run_hermit_case("reasoner.EntailmentTest.testBlankWithDTs");
}

#[test]
fn hermit_reasoner_entailmenttest_testblankwithdts2() {
    run_hermit_case("reasoner.EntailmentTest.testBlankWithDTs2");
}

#[test]
fn hermit_reasoner_entailmenttest_testblankwithdts3() {
    run_hermit_case("reasoner.EntailmentTest.testBlankWithDTs3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testinf() {
    run_hermit_case("reasoner.FloatDoubleTest.testINF");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatrange() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatRange");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatzerorange_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatZeroRange_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatzerorange_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatZeroRange_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatzerorange_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatZeroRange_3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatrangeenum() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatRangeEnum");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatnan_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatNaN_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatnan_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatNaN_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatnan_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatNaN_3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberoffloats_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfFloats_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberoffloats_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfFloats_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberoffloats_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfFloats_3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testfloatanddouble() {
    run_hermit_case("reasoner.FloatDoubleTest.testFloatAndDouble");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublerange() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleRange");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublezerorange_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleZeroRange_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublezerorange_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleZeroRange_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublezerorange_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleZeroRange_3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublerangeenum() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleRangeEnum");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublenan_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleNaN_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublenan_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleNaN_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testdoublenan_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testDoubleNaN_3");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberofdoubles_1() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfDoubles_1");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberofdoubles_2() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfDoubles_2");
}

#[test]
fn hermit_reasoner_floatdoubletest_testnumberofdoubles_3() {
    run_hermit_case("reasoner.FloatDoubleTest.testNumberOfDoubles_3");
}

#[test]
fn hermit_reasoner_numericstest_testintegerrange1() {
    run_hermit_case("reasoner.NumericsTest.testIntegerRange1");
}

#[test]
fn hermit_reasoner_numericstest_testintegerrange2_1() {
    run_hermit_case("reasoner.NumericsTest.testIntegerRange2_1");
}

#[test]
fn hermit_reasoner_numericstest_testintegerrange2_2() {
    run_hermit_case("reasoner.NumericsTest.testIntegerRange2_2");
}

#[test]
fn hermit_reasoner_numericstest_testintegerrange2_3() {
    run_hermit_case("reasoner.NumericsTest.testIntegerRange2_3");
}

#[test]
fn hermit_reasoner_numericstest_testintegerrange2_4() {
    run_hermit_case("reasoner.NumericsTest.testIntegerRange2_4");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalnotinteger_1() {
    run_hermit_case("reasoner.NumericsTest.testDecimalNotInteger_1");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalnotinteger_2() {
    run_hermit_case("reasoner.NumericsTest.testDecimalNotInteger_2");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalnotinteger_3() {
    run_hermit_case("reasoner.NumericsTest.testDecimalNotInteger_3");
}

#[test]
fn hermit_reasoner_numericstest_testrealnotdecimal() {
    run_hermit_case("reasoner.NumericsTest.testRealNotDecimal");
}

#[test]
fn hermit_reasoner_numericstest_testrealnotdecimal_2() {
    run_hermit_case("reasoner.NumericsTest.testRealNotDecimal_2");
}

#[test]
fn hermit_reasoner_numericstest_testmininclusiveint() {
    run_hermit_case("reasoner.NumericsTest.testMinInclusiveInt");
}

#[test]
fn hermit_reasoner_numericstest_testmininclusiveint_2() {
    run_hermit_case("reasoner.NumericsTest.testMinInclusiveInt_2");
}

#[test]
fn hermit_reasoner_numericstest_testminexclusivedec() {
    run_hermit_case("reasoner.NumericsTest.testMinExclusiveDec");
}

#[test]
fn hermit_reasoner_numericstest_testmaxinclusiveint() {
    run_hermit_case("reasoner.NumericsTest.testMaxInclusiveInt");
}

#[test]
fn hermit_reasoner_numericstest_testmaxinclusiveint_2() {
    run_hermit_case("reasoner.NumericsTest.testMaxInclusiveInt_2");
}

#[test]
fn hermit_reasoner_numericstest_testmaxexclusivedec() {
    run_hermit_case("reasoner.NumericsTest.testMaxExclusiveDec");
}

#[test]
fn hermit_reasoner_numericstest_testenumint_1() {
    run_hermit_case("reasoner.NumericsTest.testEnumInt_1");
}

#[test]
fn hermit_reasoner_numericstest_testenumint_2() {
    run_hermit_case("reasoner.NumericsTest.testEnumInt_2");
}

#[test]
fn hermit_reasoner_numericstest_testenumint_3() {
    run_hermit_case("reasoner.NumericsTest.testEnumInt_3");
}

#[test]
fn hermit_reasoner_numericstest_testenumint_4() {
    run_hermit_case("reasoner.NumericsTest.testEnumInt_4");
}

#[test]
fn hermit_reasoner_numericstest_testenumint_5() {
    run_hermit_case("reasoner.NumericsTest.testEnumInt_5");
}

#[test]
fn hermit_reasoner_numericstest_testenumintneq_1() {
    run_hermit_case("reasoner.NumericsTest.testEnumIntNEQ_1");
}

#[test]
fn hermit_reasoner_numericstest_testenumintneq_2() {
    run_hermit_case("reasoner.NumericsTest.testEnumIntNEQ_2");
}

#[test]
fn hermit_reasoner_numericstest_testenumintneq_3() {
    run_hermit_case("reasoner.NumericsTest.testEnumIntNEQ_3");
}

#[test]
fn hermit_reasoner_numericstest_testenumintneq_4() {
    run_hermit_case("reasoner.NumericsTest.testEnumIntNEQ_4");
}

#[test]
fn hermit_reasoner_numericstest_testenumintneq_5() {
    run_hermit_case("reasoner.NumericsTest.testEnumIntNEQ_5");
}

#[test]
fn hermit_reasoner_numericstest_testminmaxequal_1() {
    run_hermit_case("reasoner.NumericsTest.testMinMaxEqual_1");
}

#[test]
fn hermit_reasoner_numericstest_testminmaxequal_2() {
    run_hermit_case("reasoner.NumericsTest.testMinMaxEqual_2");
}

#[test]
fn hermit_reasoner_numericstest_testminmaxequal_3() {
    run_hermit_case("reasoner.NumericsTest.testMinMaxEqual_3");
}

#[test]
fn hermit_reasoner_numericstest_testminmaxequal_4() {
    run_hermit_case("reasoner.NumericsTest.testMinMaxEqual_4");
}

#[test]
fn hermit_reasoner_numericstest_testinvalidminmax() {
    run_hermit_case("reasoner.NumericsTest.testInvalidMinMax");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusint_1() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusInt_1");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusint_2() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusInt_2");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusint_3() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusInt_3");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusint_4() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusInt_4");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusintneq_1() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusIntNEQ_1");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusintneq_2() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusIntNEQ_2");
}

#[test]
fn hermit_reasoner_numericstest_testdecimalminusintneq_3() {
    run_hermit_case("reasoner.NumericsTest.testDecimalMinusIntNEQ_3");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange1_1() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange1_1");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange1_2() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange1_2");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange1_3() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange1_3");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange2_1() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange2_1");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange2_2() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange2_2");
}

#[test]
fn hermit_reasoner_numericstest_testlargerange2_3() {
    run_hermit_case("reasoner.NumericsTest.testLargeRange2_3");
}

#[test]
fn hermit_reasoner_numericstest_testclique() {
    run_hermit_case("reasoner.NumericsTest.testClique");
}

#[test]
fn hermit_reasoner_owlreasonertest_testbottomobjectpropertysubs() {
    run_hermit_case("reasoner.OWLReasonerTest.testBottomObjectPropertySubs");
}

#[test]
fn hermit_reasoner_owlreasonertest_testtopobjectpropertysupers() {
    run_hermit_case("reasoner.OWLReasonerTest.testTopObjectPropertySupers");
}

#[test]
fn hermit_reasoner_owlreasonertest_testincrementaladdition() {
    run_hermit_case("reasoner.OWLReasonerTest.testIncrementalAddition");
}

#[test]
fn hermit_reasoner_owlreasonertest_testincrementaladdition2() {
    run_hermit_case("reasoner.OWLReasonerTest.testIncrementalAddition2");
}

#[test]
fn hermit_reasoner_owlreasonertest_testgetdatapropertyvalues() {
    run_hermit_case("reasoner.OWLReasonerTest.testGetDataPropertyValues");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testlength_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testLength_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testlength_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testLength_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testlength_3() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testLength_3");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testlength_4() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testLength_4");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testlength_5() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testLength_5");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testsize_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testSize_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testsize_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testSize_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testsize_3() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testSize_3");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testintersection_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testIntersection_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testintersection_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testIntersection_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpattern1_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPattern1_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpattern1_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPattern1_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpattern2_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPattern2_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpattern2_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPattern2_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpattern3() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPattern3");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatternandlength1_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternAndLength1_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatternandlength1_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternAndLength1_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatternandlength1_3() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternAndLength1_3");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatterncomplement1_1() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternComplement1_1");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatterncomplement1_2() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternComplement1_2");
}

#[test]
fn hermit_reasoner_rdfplainliteraltest_testpatterncomplement1_3() {
    run_hermit_case("reasoner.RDFPlainLiteralTest.testPatternComplement1_3");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity0() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity0");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity1() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity1");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity2() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity2");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity3() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity3");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity4() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity4");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity5() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity5");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity6() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity6");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity7() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity7");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity8() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity8");
}

#[test]
fn hermit_reasoner_riaregularitytest_testriaregularity9() {
    run_hermit_case("reasoner.RIARegularityTest.testRIARegularity9");
}

#[test]
fn hermit_reasoner_reasonercoreblockingtest_testexpansion() {
    run_hermit_case("reasoner.ReasonerCoreBlockingTest.testExpansion");
}

#[test]
fn hermit_reasoner_reasonercoreblockingtest_testwidmann2() {
    run_hermit_case("reasoner.ReasonerCoreBlockingTest.testWidmann2");
}

#[test]
fn hermit_reasoner_reasonercoreblockingtest_testiant6() {
    run_hermit_case("reasoner.ReasonerCoreBlockingTest.testIanT6");
}

#[test]
fn hermit_reasoner_reasonercoreblockingtest_testiant9() {
    run_hermit_case("reasoner.ReasonerCoreBlockingTest.testIanT9");
}

#[test]
fn hermit_reasoner_reasonertest_testisentailed() {
    run_hermit_case("reasoner.ReasonerTest.testIsEntailed");
}

#[test]
fn hermit_reasoner_reasonertest_testuniversalrolepartitionedabox() {
    run_hermit_case("reasoner.ReasonerTest.testUniversalRolePartitionedABox");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithsameas() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithSameAs");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithnegatedhasvalue() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithNegatedHasValue");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithhasvalue() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithHasValue");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithnegatedclass() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithNegatedClass");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithclass() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithClass");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithnegatedhasself() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithNegatedHasSelf");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithhasself() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithHasSelf");
}

#[test]
fn hermit_reasoner_reasonertest_testincrementalwithfreshnames() {
    run_hermit_case("reasoner.ReasonerTest.testIncrementalWithFreshNames");
}

#[test]
fn hermit_reasoner_reasonertest_testtopopequivalence() {
    run_hermit_case("reasoner.ReasonerTest.testTopOPEquivalence");
}

#[test]
fn hermit_reasoner_reasonertest_testfreshentityentailment() {
    run_hermit_case("reasoner.ReasonerTest.testFreshEntityEntailment");
}

#[test]
fn hermit_reasoner_reasonertest_testuniversalrolesubsumption() {
    run_hermit_case("reasoner.ReasonerTest.testUniversalRoleSubsumption");
}

#[test]
fn hermit_reasoner_reasonertest_testprecomputedisjointclasses() {
    run_hermit_case("reasoner.ReasonerTest.testPrecomputeDisjointClasses");
}

#[test]
fn hermit_reasoner_reasonertest_testkeys3() {
    run_hermit_case("reasoner.ReasonerTest.testKeys3");
}

#[test]
fn hermit_reasoner_reasonertest_testequivalentclassinstances() {
    run_hermit_case("reasoner.ReasonerTest.testEquivalentClassInstances");
}

#[test]
fn hermit_reasoner_reasonertest_testobjectpropertysubsumptionsnonominals() {
    run_hermit_case("reasoner.ReasonerTest.testObjectPropertySubsumptionsNoNominals");
}

#[test]
fn hermit_reasoner_reasonertest_testobjectpropertysubsumptionsnominals() {
    run_hermit_case("reasoner.ReasonerTest.testObjectPropertySubsumptionsNominals");
}

#[test]
fn hermit_reasoner_reasonertest_testbottomobjectpropertyassertion() {
    run_hermit_case("reasoner.ReasonerTest.testBottomObjectPropertyAssertion");
}

#[test]
fn hermit_reasoner_reasonertest_testdatapropertyentailment() {
    run_hermit_case("reasoner.ReasonerTest.testDataPropertyEntailment");
}

#[test]
fn hermit_reasoner_reasonertest_testpropertyinstanceretrieval() {
    run_hermit_case("reasoner.ReasonerTest.testPropertyInstanceRetrieval");
}

#[test]
fn hermit_reasoner_reasonertest_testclassificationsubclassbug() {
    run_hermit_case("reasoner.ReasonerTest.testClassificationSubClassBug");
}

#[test]
fn hermit_reasoner_reasonertest_testnegativeobjectpropertyassertionwithnonsimple() {
    run_hermit_case("reasoner.ReasonerTest.testNegativeObjectPropertyAssertionWithNonSimple");
}

#[test]
fn hermit_reasoner_reasonertest_testpropertyenailmentfromalan() {
    run_hermit_case("reasoner.ReasonerTest.testPropertyEnailmentFromAlan");
}

#[test]
fn hermit_reasoner_reasonertest_testsubproperties() {
    run_hermit_case("reasoner.ReasonerTest.testSubProperties");
}

#[test]
fn hermit_reasoner_reasonertest_testunknownclasshierarcyposition() {
    run_hermit_case("reasoner.ReasonerTest.testUnknownClassHierarcyPosition");
}

#[test]
fn hermit_reasoner_reasonertest_testunknowndatatypes() {
    run_hermit_case("reasoner.ReasonerTest.testUnknownDatatypes");
}

#[test]
fn hermit_reasoner_reasonertest_testrolechains() {
    run_hermit_case("reasoner.ReasonerTest.testRoleChains");
}

#[test]
fn hermit_reasoner_reasonertest_testrolechainswithtransitivesymmetric() {
    run_hermit_case("reasoner.ReasonerTest.testRoleChainsWithTransitiveSymmetric");
}

#[test]
fn hermit_reasoner_reasonertest_testrolesubsumptionwithchainstransitivesymmetric() {
    run_hermit_case("reasoner.ReasonerTest.testRoleSubsumptionWithChainsTransitiveSymmetric");
}

#[test]
fn hermit_reasoner_reasonertest_testrolesubsumption() {
    run_hermit_case("reasoner.ReasonerTest.testRoleSubsumption");
}

#[test]
fn hermit_reasoner_reasonertest_testisfunctionaldata() {
    run_hermit_case("reasoner.ReasonerTest.testIsFunctionalData");
}

#[test]
fn hermit_reasoner_reasonertest_testisfunctionalobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsFunctionalObject");
}

#[test]
fn hermit_reasoner_reasonertest_testisinversefunctionalobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsInverseFunctionalObject");
}

#[test]
fn hermit_reasoner_reasonertest_testisreflexiveobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsReflexiveObject");
}

#[test]
fn hermit_reasoner_reasonertest_testisirreflexiveobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsIrreflexiveObject");
}

#[test]
fn hermit_reasoner_reasonertest_testissymmetricobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsSymmetricObject");
}

#[test]
fn hermit_reasoner_reasonertest_testisasymmetricobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsAsymmetricObject");
}

#[test]
fn hermit_reasoner_reasonertest_testistransitiveobject() {
    run_hermit_case("reasoner.ReasonerTest.testIsTransitiveObject");
}

#[test]
fn hermit_reasoner_reasonertest_testlearningbacktracking() {
    run_hermit_case("reasoner.ReasonerTest.testLearningBacktracking");
}

#[test]
fn hermit_reasoner_reasonertest_testobjectpropertydomainstimothybug() {
    run_hermit_case("reasoner.ReasonerTest.testObjectPropertyDomainsTimothyBug");
}

#[test]
fn hermit_reasoner_reasonertest_testindividualretrieval() {
    run_hermit_case("reasoner.ReasonerTest.testIndividualRetrieval");
}

#[test]
fn hermit_reasoner_reasonertest_testdatatyperestriction() {
    run_hermit_case("reasoner.ReasonerTest.testDataTypeRestriction");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindividualconstraints() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndividualConstraints");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindividualconstraints2() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndividualConstraints2");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindividualconstraints3() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndividualConstraints3");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindividualconstraints4() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndividualConstraints4");
}

#[test]
fn hermit_reasoner_reasonertest_testtransitivity() {
    run_hermit_case("reasoner.ReasonerTest.testTransitivity");
}

#[test]
fn hermit_reasoner_reasonertest_testsubroleschain() {
    run_hermit_case("reasoner.ReasonerTest.testSubRolesChain");
}

#[test]
fn hermit_reasoner_reasonertest_testhaskeyentailment() {
    run_hermit_case("reasoner.ReasonerTest.testHasKeyEntailment");
}

#[test]
fn hermit_reasoner_reasonertest_testhaskeynonentailment() {
    run_hermit_case("reasoner.ReasonerTest.testHasKeyNonEntailment");
}

#[test]
fn hermit_reasoner_reasonertest_testdatatypedefentailment() {
    run_hermit_case("reasoner.ReasonerTest.testDatatypeDefEntailment");
}

#[test]
fn hermit_reasoner_reasonertest_testdomainrange() {
    run_hermit_case("reasoner.ReasonerTest.testDomainRange");
}

#[test]
fn hermit_reasoner_reasonertest_testdatetime2() {
    run_hermit_case("reasoner.ReasonerTest.testDateTime2");
}

#[test]
fn hermit_reasoner_reasonertest_testchains1() {
    run_hermit_case("reasoner.ReasonerTest.testChains1");
}

#[test]
fn hermit_reasoner_reasonertest_testchains2() {
    run_hermit_case("reasoner.ReasonerTest.testChains2");
}

#[test]
fn hermit_reasoner_reasonertest_testchains3() {
    run_hermit_case("reasoner.ReasonerTest.testChains3");
}

#[test]
fn hermit_reasoner_reasonertest_testchains4() {
    run_hermit_case("reasoner.ReasonerTest.testChains4");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindiviuals1() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndiviuals1");
}

#[test]
fn hermit_reasoner_reasonertest_testdatetime() {
    run_hermit_case("reasoner.ReasonerTest.testDateTime");
}

#[test]
fn hermit_reasoner_reasonertest_testdataranges() {
    run_hermit_case("reasoner.ReasonerTest.testDataRanges");
}

#[test]
fn hermit_reasoner_reasonertest_testbottomdataproperty() {
    run_hermit_case("reasoner.ReasonerTest.testBottomDataProperty");
}

#[test]
fn hermit_reasoner_reasonertest_testchains() {
    run_hermit_case("reasoner.ReasonerTest.testChains");
}

#[test]
fn hermit_reasoner_reasonertest_testhaskeysonlynamed() {
    run_hermit_case("reasoner.ReasonerTest.testHasKeysOnlyNamed");
}

#[test]
fn hermit_reasoner_reasonertest_testnegativedatapropertyassertion() {
    run_hermit_case("reasoner.ReasonerTest.testNegativeDataPropertyAssertion");
}

#[test]
fn hermit_reasoner_reasonertest_testkeys() {
    run_hermit_case("reasoner.ReasonerTest.testKeys");
}

#[test]
fn hermit_reasoner_reasonertest_testkeysnegatedclass() {
    run_hermit_case("reasoner.ReasonerTest.testKeysNegatedClass");
}

#[test]
fn hermit_reasoner_reasonertest_testnonunarykeys() {
    run_hermit_case("reasoner.ReasonerTest.testNonUnaryKeys");
}

#[test]
fn hermit_reasoner_reasonertest_testnonunarykeys2() {
    run_hermit_case("reasoner.ReasonerTest.testNonUnaryKeys2");
}

#[test]
fn hermit_reasoner_reasonertest_testhierarchyprinting3() {
    run_hermit_case("reasoner.ReasonerTest.testHierarchyPrinting3");
}

#[test]
fn hermit_reasoner_reasonertest_testobjectpropertyhierarchy() {
    run_hermit_case("reasoner.ReasonerTest.testObjectPropertyHierarchy");
}

#[test]
fn hermit_reasoner_reasonertest_testsemanticobjectpropertyclassification() {
    run_hermit_case("reasoner.ReasonerTest.testSemanticObjectPropertyClassification");
}

#[test]
fn hermit_reasoner_reasonertest_testdatapropertyhierarchy() {
    run_hermit_case("reasoner.ReasonerTest.testDataPropertyHierarchy");
}

#[test]
fn hermit_reasoner_reasonertest_testdatapropertysemantics() {
    run_hermit_case("reasoner.ReasonerTest.testDataPropertySemantics");
}

#[test]
fn hermit_reasoner_reasonertest_testsemanticdatapropertyclassification() {
    run_hermit_case("reasoner.ReasonerTest.testSemanticDataPropertyClassification");
}

#[test]
fn hermit_reasoner_reasonertest_testcomplexconceptinstanceretrieval() {
    run_hermit_case("reasoner.ReasonerTest.testComplexConceptInstanceRetrieval");
}

#[test]
fn hermit_reasoner_reasonertest_testwidmann1() {
    run_hermit_case("reasoner.ReasonerTest.testWidmann1");
}

#[test]
fn hermit_reasoner_reasonertest_testwidmann2() {
    run_hermit_case("reasoner.ReasonerTest.testWidmann2");
}

#[test]
fn hermit_reasoner_reasonertest_testwidmann3() {
    run_hermit_case("reasoner.ReasonerTest.testWidmann3");
}

#[test]
fn hermit_reasoner_reasonertest_testreflexivity() {
    run_hermit_case("reasoner.ReasonerTest.testReflexivity");
}

#[test]
fn hermit_reasoner_reasonertest_testnegproperties() {
    run_hermit_case("reasoner.ReasonerTest.testNegProperties");
}

#[test]
fn hermit_reasoner_reasonertest_testirreflexivity() {
    run_hermit_case("reasoner.ReasonerTest.testIrreflexivity");
}

#[test]
fn hermit_reasoner_reasonertest_testroledisjointness_1() {
    run_hermit_case("reasoner.ReasonerTest.testRoleDisjointness_1");
}

#[test]
fn hermit_reasoner_reasonertest_testroledisjointness_2() {
    run_hermit_case("reasoner.ReasonerTest.testRoleDisjointness_2");
}

#[test]
fn hermit_reasoner_reasonertest_testroledisjointness2() {
    run_hermit_case("reasoner.ReasonerTest.testRoleDisjointness2");
}

#[test]
fn hermit_reasoner_reasonertest_testexistsself1() {
    run_hermit_case("reasoner.ReasonerTest.testExistsSelf1");
}

#[test]
fn hermit_reasoner_reasonertest_testexistsself2() {
    run_hermit_case("reasoner.ReasonerTest.testExistsSelf2");
}

#[test]
fn hermit_reasoner_reasonertest_testasymmetry() {
    run_hermit_case("reasoner.ReasonerTest.testAsymmetry");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiability1() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiability1");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiability2() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiability2");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiability3() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiability3");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiability4() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiability4");
}

#[test]
fn hermit_reasoner_reasonertest_testchanges() {
    run_hermit_case("reasoner.ReasonerTest.testChanges");
}

#[test]
fn hermit_reasoner_reasonertest_testsubsumption1() {
    run_hermit_case("reasoner.ReasonerTest.testSubsumption1");
}

#[test]
fn hermit_reasoner_reasonertest_testsubsumption2() {
    run_hermit_case("reasoner.ReasonerTest.testSubsumption2");
}

#[test]
fn hermit_reasoner_reasonertest_testsubsumption3() {
    run_hermit_case("reasoner.ReasonerTest.testSubsumption3");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox1() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox1");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox2() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox2");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox3c() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox3c");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox3cirh() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox3cIrh");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox3() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox3");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox3modified() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox3Modified");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox4a() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox4a");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox4b() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox4b");
}

#[test]
fn hermit_reasoner_reasonertest_testheinsohntbox7() {
    run_hermit_case("reasoner.ReasonerTest.testHeinsohnTBox7");
}

#[test]
fn hermit_reasoner_reasonertest_testiant1a() {
    run_hermit_case("reasoner.ReasonerTest.testIanT1a");
}

#[test]
fn hermit_reasoner_reasonertest_testiant1b() {
    run_hermit_case("reasoner.ReasonerTest.testIanT1b");
}

#[test]
fn hermit_reasoner_reasonertest_testiant1c() {
    run_hermit_case("reasoner.ReasonerTest.testIanT1c");
}

#[test]
fn hermit_reasoner_reasonertest_testiant2() {
    run_hermit_case("reasoner.ReasonerTest.testIanT2");
}

#[test]
fn hermit_reasoner_reasonertest_testiant3() {
    run_hermit_case("reasoner.ReasonerTest.testIanT3");
}

#[test]
fn hermit_reasoner_reasonertest_testiant4() {
    run_hermit_case("reasoner.ReasonerTest.testIanT4");
}

#[test]
fn hermit_reasoner_reasonertest_testiant5() {
    run_hermit_case("reasoner.ReasonerTest.testIanT5");
}

#[test]
fn hermit_reasoner_reasonertest_testiant6() {
    run_hermit_case("reasoner.ReasonerTest.testIanT6");
}

#[test]
fn hermit_reasoner_reasonertest_testiant7a() {
    run_hermit_case("reasoner.ReasonerTest.testIanT7a");
}

#[test]
fn hermit_reasoner_reasonertest_testiant7b() {
    run_hermit_case("reasoner.ReasonerTest.testIanT7b");
}

#[test]
fn hermit_reasoner_reasonertest_testiant7c() {
    run_hermit_case("reasoner.ReasonerTest.testIanT7c");
}

#[test]
fn hermit_reasoner_reasonertest_testiant8a() {
    run_hermit_case("reasoner.ReasonerTest.testIanT8a");
}

#[test]
fn hermit_reasoner_reasonertest_testiant8() {
    run_hermit_case("reasoner.ReasonerTest.testIanT8");
}

#[test]
fn hermit_reasoner_reasonertest_testiant9() {
    run_hermit_case("reasoner.ReasonerTest.testIanT9");
}

#[test]
fn hermit_reasoner_reasonertest_testiant10() {
    run_hermit_case("reasoner.ReasonerTest.testIanT10");
}

#[test]
fn hermit_reasoner_reasonertest_testiant11() {
    run_hermit_case("reasoner.ReasonerTest.testIanT11");
}

#[test]
fn hermit_reasoner_reasonertest_testiant12() {
    run_hermit_case("reasoner.ReasonerTest.testIanT12");
}

#[test]
fn hermit_reasoner_reasonertest_testiant13() {
    run_hermit_case("reasoner.ReasonerTest.testIanT13");
}

#[test]
fn hermit_reasoner_reasonertest_testianfact1() {
    run_hermit_case("reasoner.ReasonerTest.testIanFact1");
}

#[test]
fn hermit_reasoner_reasonertest_testianfact2() {
    run_hermit_case("reasoner.ReasonerTest.testIanFact2");
}

#[test]
fn hermit_reasoner_reasonertest_testianfact3() {
    run_hermit_case("reasoner.ReasonerTest.testIanFact3");
}

#[test]
fn hermit_reasoner_reasonertest_testianfact4() {
    run_hermit_case("reasoner.ReasonerTest.testIanFact4");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug1b() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug1b");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug4() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug4");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug5() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug5");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug6() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug6");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug7() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug7");
}

#[test]
fn hermit_reasoner_reasonertest_testianbug8() {
    run_hermit_case("reasoner.ReasonerTest.testIanBug8");
}

#[test]
fn hermit_reasoner_reasonertest_testianmergetest1() {
    run_hermit_case("reasoner.ReasonerTest.testIanMergeTest1");
}

#[test]
fn hermit_reasoner_reasonertest_testianmergetest2() {
    run_hermit_case("reasoner.ReasonerTest.testIanMergeTest2");
}

#[test]
fn hermit_reasoner_reasonertest_testianqnrtest() {
    run_hermit_case("reasoner.ReasonerTest.testIanQNRTest");
}

#[test]
fn hermit_reasoner_reasonertest_testianrecursivedefinitiontest1() {
    run_hermit_case("reasoner.ReasonerTest.testIanRecursiveDefinitionTest1");
}

#[test]
fn hermit_reasoner_reasonertest_testianrecursivedefinitiontest2() {
    run_hermit_case("reasoner.ReasonerTest.testIanRecursiveDefinitionTest2");
}

#[test]
fn hermit_reasoner_reasonertest_testianrecursivedefinitiontest3() {
    run_hermit_case("reasoner.ReasonerTest.testIanRecursiveDefinitionTest3");
}

#[test]
fn hermit_reasoner_reasonertest_testianbackjumping1() {
    run_hermit_case("reasoner.ReasonerTest.testIanBackjumping1");
}

#[test]
fn hermit_reasoner_reasonertest_testianbackjumping2() {
    run_hermit_case("reasoner.ReasonerTest.testIanBackjumping2");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals1() {
    run_hermit_case("reasoner.ReasonerTest.testNominals1");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals2() {
    run_hermit_case("reasoner.ReasonerTest.testNominals2");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals3() {
    run_hermit_case("reasoner.ReasonerTest.testNominals3");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals4() {
    run_hermit_case("reasoner.ReasonerTest.testNominals4");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals5() {
    run_hermit_case("reasoner.ReasonerTest.testNominals5");
}

#[test]
fn hermit_reasoner_reasonertest_testnominals6() {
    run_hermit_case("reasoner.ReasonerTest.testNominals6");
}

#[test]
fn hermit_reasoner_reasonertest_testnovelnominals() {
    run_hermit_case("reasoner.ReasonerTest.testNovelNominals");
}

#[test]
fn hermit_reasoner_reasonertest_testkeys1() {
    run_hermit_case("reasoner.ReasonerTest.testKeys1");
}

#[test]
fn hermit_reasoner_reasonertest_testkeys2() {
    run_hermit_case("reasoner.ReasonerTest.testKeys2");
}

#[test]
fn hermit_reasoner_reasonertest_testnominalmerging() {
    run_hermit_case("reasoner.ReasonerTest.testNominalMerging");
}

#[test]
fn hermit_reasoner_reasonertest_testniruleblockingwithunraveling() {
    run_hermit_case("reasoner.ReasonerTest.testNIRuleBlockingWithUnraveling");
}

#[test]
fn hermit_reasoner_reasonertest_testpunning() {
    run_hermit_case("reasoner.ReasonerTest.testPunning");
}

#[test]
fn hermit_reasoner_reasonertest_testpunning2() {
    run_hermit_case("reasoner.ReasonerTest.testPunning2");
}

#[test]
fn hermit_reasoner_reasonertest_testpunning3() {
    run_hermit_case("reasoner.ReasonerTest.testPunning3");
}

#[test]
fn hermit_reasoner_reasonertest_testinverses2() {
    run_hermit_case("reasoner.ReasonerTest.testInverses2");
}

#[test]
fn hermit_reasoner_reasonertest_testmissingcbug() {
    run_hermit_case("reasoner.ReasonerTest.testMissingCBug");
}

#[test]
fn hermit_reasoner_reasonertest_testinverses() {
    run_hermit_case("reasoner.ReasonerTest.testInverses");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindiviuals2() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndiviuals2");
}

#[test]
fn hermit_reasoner_reasonertest_testanonymousindiviuals3() {
    run_hermit_case("reasoner.ReasonerTest.testAnonymousIndiviuals3");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias1() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs1");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias2() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs2");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias3() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs3");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias4() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs4");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias5() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs5");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias6() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs6");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias7() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs7");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias8() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs8");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias9() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs9");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias10() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs10");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias11() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs11");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias11b() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs11b");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias12() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs12");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias13() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs13");
}

#[test]
fn hermit_reasoner_reasonertest_testsatisfiabilitywithrias14() {
    run_hermit_case("reasoner.ReasonerTest.testSatisfiabilityWithRIAs14");
}

#[test]
fn hermit_reasoner_rulestest_testsameasinbody1() {
    run_hermit_case("reasoner.RulesTest.testSameAsInBody1");
}

#[test]
fn hermit_reasoner_rulestest_testsameasinbody2() {
    run_hermit_case("reasoner.RulesTest.testSameAsInBody2");
}

#[test]
fn hermit_reasoner_rulestest_testsameasinbodywithdataproperties() {
    run_hermit_case("reasoner.RulesTest.testSameAsInBodyWithDataProperties");
}

#[test]
fn hermit_reasoner_rulestest_testdatapropertiesinbody() {
    run_hermit_case("reasoner.RulesTest.testDataPropertiesInBody");
}

#[test]
fn hermit_reasoner_rulestest_testindividualsinrules() {
    run_hermit_case("reasoner.RulesTest.testIndividualsInRules");
}

#[test]
fn hermit_reasoner_rulestest_testrulenonsimple() {
    run_hermit_case("reasoner.RulesTest.testRuleNonSimple");
}

#[test]
fn hermit_reasoner_rulestest_testrulenotaxiom() {
    run_hermit_case("reasoner.RulesTest.testRuleNotAxiom");
}

#[test]
fn hermit_reasoner_rulestest_testsimplerule2() {
    run_hermit_case("reasoner.RulesTest.testSimpleRule2");
}

#[test]
fn hermit_reasoner_rulestest_testsimplerule() {
    run_hermit_case("reasoner.RulesTest.testSimpleRule");
}

#[test]
fn hermit_reasoner_rulestest_testrulewithconstants() {
    run_hermit_case("reasoner.RulesTest.testRuleWithConstants");
}

#[test]
fn hermit_reasoner_rulestest_testrulewithconstants2() {
    run_hermit_case("reasoner.RulesTest.testRuleWithConstants2");
}

#[test]
fn hermit_reasoner_rulestest_testrulewithdatatypes() {
    run_hermit_case("reasoner.RulesTest.testRuleWithDatatypes");
}

#[test]
fn hermit_reasoner_rulestest_testrulewithdatatypes2() {
    run_hermit_case("reasoner.RulesTest.testRuleWithDatatypes2");
}

#[test]
fn hermit_reasoner_rulestest_testrulewithfreshindividuals() {
    run_hermit_case("reasoner.RulesTest.testRuleWithFreshIndividuals");
}

#[test]
fn hermit_reasoner_rulestest_testaddingfactsbyrules() {
    run_hermit_case("reasoner.RulesTest.testAddingFactsByRules");
}

#[test]
fn hermit_reasoner_rulestest_testlloydtopor() {
    run_hermit_case("reasoner.RulesTest.testLloydTopor");
}

#[test]
fn hermit_reasoner_rulestest_testdatarangesafety() {
    run_hermit_case("reasoner.RulesTest.testDataRangeSafety");
}

#[test]
fn hermit_reasoner_rulestest_testseveralvars() {
    run_hermit_case("reasoner.RulesTest.testSeveralVars");
}

#[test]
fn hermit_reasoner_rulestest_testpositivebodydatarange() {
    run_hermit_case("reasoner.RulesTest.testPositiveBodyDataRange");
}

#[test]
fn hermit_reasoner_rulestest_testnegativebodydatarange() {
    run_hermit_case("reasoner.RulesTest.testNegativeBodyDataRange");
}

#[test]
fn hermit_reasoner_rulestest_testnegdrinhead() {
    run_hermit_case("reasoner.RulesTest.testNegDRInHead");
}

#[test]
fn hermit_reasoner_rulestest_testsameas() {
    run_hermit_case("reasoner.RulesTest.testSameAs");
}

#[test]
fn hermit_reasoner_rulestest_testdifferentfrom() {
    run_hermit_case("reasoner.RulesTest.testDifferentFrom");
}

#[test]
fn hermit_reasoner_rulestest_testdiffrentfrom2() {
    run_hermit_case("reasoner.RulesTest.testDiffrentFrom2");
}

#[test]
fn hermit_reasoner_simplerolestest_testsimpleroles1() {
    run_hermit_case("reasoner.SimpleRolesTest.testSimpleRoles1");
}

#[test]
fn hermit_reasoner_simplerolestest_testsimpleroles2() {
    run_hermit_case("reasoner.SimpleRolesTest.testSimpleRoles2");
}

#[test]
fn hermit_reasoner_simplerolestest_testsimpleroles3() {
    run_hermit_case("reasoner.SimpleRolesTest.testSimpleRoles3");
}

#[test]
fn hermit_reasoner_simplerolestest_testsimpleroles4() {
    run_hermit_case("reasoner.SimpleRolesTest.testSimpleRoles4");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testcanonicalization_1() {
    run_hermit_case("reasoner.XMLLiteralTest.testCanonicalization_1");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testcanonicalization_2() {
    run_hermit_case("reasoner.XMLLiteralTest.testCanonicalization_2");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testrange_1() {
    run_hermit_case("reasoner.XMLLiteralTest.testRange_1");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testrange_2() {
    run_hermit_case("reasoner.XMLLiteralTest.testRange_2");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testrange_3() {
    run_hermit_case("reasoner.XMLLiteralTest.testRange_3");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testmembership_1() {
    run_hermit_case("reasoner.XMLLiteralTest.testMembership_1");
}

#[test]
fn hermit_reasoner_xmlliteraltest_testmembership_2() {
    run_hermit_case("reasoner.XMLLiteralTest.testMembership_2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertieshasvalue1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesHasValue1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertieshasvalue2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesHasValue2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesall1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesAll1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesall2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesAll2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiessome1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesSome1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiessome2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesSome2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdataoneof1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataOneOf1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdataoneof2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataOneOf2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdataoneof3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataOneOf3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdataoneof4() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataOneOf4");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdatacomplementof1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataComplementOf1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesdatacomplementof2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesDataComplementOf2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmax1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMax1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmax2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMax2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmax3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMax3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmax4() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMax4");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmin1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMin1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmin2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMin2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmin3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMin3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesmin4() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesMin4");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesexact1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesExact1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesexact2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesExact2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesexact3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesExact3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatapropertiesexact4() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataPropertiesExact4");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdataintersectionof() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataIntersectionOf");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdataintersectionof2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataIntersectionOf2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdataintersectionof3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataIntersectionOf3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdataunionof1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataUnionOf1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatacomplementof1() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataComplementOf1");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatacomplementof2() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataComplementOf2");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatacomplementof3() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataComplementOf3");
}

#[test]
fn hermit_structural_clausificationdatatypestest_testdatacomplementof4() {
    run_hermit_case("structural.ClausificationDatatypesTest.testDataComplementOf4");
}

#[test]
fn hermit_structural_clausificationtest_testasymmetry() {
    run_hermit_case("structural.ClausificationTest.testAsymmetry");
}
