// Auto-generated by tests/hermit/generate_catalog.py — do not edit.

use ontologos_conformance::run_wg_case;

#[test]
fn hermit_owl_wg_tests_bnode2somevaluesfrom() {
    run_wg_case("owl_wg_tests.Bnode2somevaluesfrom");
}

#[test]
fn hermit_owl_wg_tests_chain2trans() {
    run_wg_case("owl_wg_tests.Chain2trans");
}

#[test]
fn hermit_owl_wg_tests_datatype_2drestrictions_2ddifferent_2dtypes() {
    run_wg_case("owl_wg_tests.Datatype-2Drestrictions-2Ddifferent-2Dtypes");
}

#[test]
fn hermit_owl_wg_tests_owlreal_2dplus_2doneof() {
    run_wg_case("owl_wg_tests.Owlreal-2Dplus-2DoneOf");
}

#[test]
fn hermit_owl_wg_tests_consistent_2dbut_2dall_2dunsat() {
    run_wg_case("owl_wg_tests.Consistent-2Dbut-2Dall-2Dunsat");
}

#[test]
fn hermit_owl_wg_tests_consistent_2ddataproperty_2ddisjointness() {
    run_wg_case("owl_wg_tests.Consistent-2Ddataproperty-2Ddisjointness");
}

#[test]
fn hermit_owl_wg_tests_consistent_2ddatetime() {
    run_wg_case("owl_wg_tests.Consistent-2DdateTime");
}

#[test]
fn hermit_owl_wg_tests_consistent_2dinteger_2dfiller() {
    run_wg_case("owl_wg_tests.Consistent-2Dinteger-2Dfiller");
}

#[test]
fn hermit_owl_wg_tests_contradicting_2ddatatype_2drestrictions() {
    run_wg_case("owl_wg_tests.Contradicting-2Ddatatype-2Drestrictions");
}

#[test]
fn hermit_owl_wg_tests_contradicting_2ddatetime_2drestrictions() {
    run_wg_case("owl_wg_tests.Contradicting-2DdateTime-2Drestrictions");
}

#[test]
fn hermit_owl_wg_tests_datatype_2ddatacomplementof_2d001() {
    run_wg_case("owl_wg_tests.Datatype-2DDataComplementOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_datatype_2dfloat_2ddiscrete_2d001() {
    run_wg_case("owl_wg_tests.Datatype-2DFloat-2DDiscrete-2D001");
}

#[test]
fn hermit_owl_wg_tests_datatype_2drestriction_2dmin_2dmax_2dinconsistency() {
    run_wg_case("owl_wg_tests.Datatype-2Drestriction-2Dmin-2Dmax-2Dinconsistency");
}

#[test]
fn hermit_owl_wg_tests_different_2dtypes_2dplus_2dcomplement() {
    run_wg_case("owl_wg_tests.Different-2Dtypes-2Dplus-2Dcomplement");
}

#[test]
fn hermit_owl_wg_tests_disjoint_props_via_disjoint_domains() {
    run_wg_case("owl_wg_tests.Disjoint_Props_via_Disjoint_Domains");
}

#[test]
fn hermit_owl_wg_tests_disjoint_props_via_disjoint_ranges() {
    run_wg_case("owl_wg_tests.Disjoint_Props_via_Disjoint_Ranges");
}

#[test]
fn hermit_owl_wg_tests_disjointclasses_2d001() {
    run_wg_case("owl_wg_tests.DisjointClasses-2D001");
}

#[test]
fn hermit_owl_wg_tests_disjointclasses_2d002() {
    run_wg_case("owl_wg_tests.DisjointClasses-2D002");
}

#[test]
fn hermit_owl_wg_tests_disjointclasses_2d003() {
    run_wg_case("owl_wg_tests.DisjointClasses-2D003");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2ddifferent_2dindividuals_2d2_2dannotation_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Ddifferent-2Dindividuals-2D2-2Dannotation-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2ddifferent_2dindividuals_2d2_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Ddifferent-2Dindividuals-2D2-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2ddifferent_2dindividuals_2d3_2dannotation_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Ddifferent-2Dindividuals-2D3-2Dannotation-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2ddifferent_2dindividuals_2d3_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Ddifferent-2Dindividuals-2D3-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2dno_2dbuiltin_2dprefixes_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Dno-2Dbuiltin-2Dprefixes-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2dpropertychain_2d2_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Dpropertychain-2D2-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2dsame_2dindividual_2d2_2dannotation_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Dsame-2Dindividual-2D2-2Dannotation-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2dsame_2dindividual_2d2_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Dsame-2Dindividual-2D2-2Dar");
}

#[test]
fn hermit_owl_wg_tests_fs2rdf_2dsame_2dindividual_2d3_2dannotation_2dar() {
    run_wg_case("owl_wg_tests.FS2RDF-2Dsame-2Dindividual-2D3-2Dannotation-2Dar");
}

#[test]
fn hermit_owl_wg_tests_footnote_2dnot_2dabout_2dself() {
    run_wg_case("owl_wg_tests.Footnote-2Dnot-2Dabout-2Dself");
}

#[test]
fn hermit_owl_wg_tests_functionality_2dclash() {
    run_wg_case("owl_wg_tests.Functionality-2Dclash");
}

#[test]
fn hermit_owl_wg_tests_inconsistent_2dbyte_2dfiller() {
    run_wg_case("owl_wg_tests.Inconsistent-2Dbyte-2Dfiller");
}

#[test]
fn hermit_owl_wg_tests_datacomplement_2dplus_2drestrictions() {
    run_wg_case("owl_wg_tests.Datacomplement-2Dplus-2Drestrictions");
}

#[test]
fn hermit_owl_wg_tests_inconsistent_2ddisjoint_2ddataproperties() {
    run_wg_case("owl_wg_tests.Inconsistent-2Ddisjoint-2Ddataproperties");
}

#[test]
fn hermit_owl_wg_tests_inconsistent_2dpattern_2ddisjointness() {
    run_wg_case("owl_wg_tests.Inconsistent-2Dpattern-2Ddisjointness");
}

#[test]
fn hermit_owl_wg_tests_inconsistent_2dinteger_2dfiller() {
    run_wg_case("owl_wg_tests.Inconsistent-2Dinteger-2Dfiller");
}

#[test]
fn hermit_owl_wg_tests_inconsistent_datatypes() {
    run_wg_case("owl_wg_tests.Inconsistent_datatypes");
}

#[test]
fn hermit_owl_wg_tests_individual_2dclass_punning_vs_objectoneof() {
    run_wg_case("owl_wg_tests.Individual-2DClass_Punning_vs._ObjectOneOf");
}

#[test]
fn hermit_owl_wg_tests_minus_2dinf_2dnot_2dowlreal() {
    run_wg_case("owl_wg_tests.Minus-2Dinf-2Dnot-2Dowlreal");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dannotationannotations_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DAnnotationAnnotations-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dasymmetricproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DAsymmetricProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2daxiomannotations_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DAxiomAnnotations-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dbottomdataproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DBottomDataProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dbottomobjectproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DBottomObjectProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddataqcr_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDataQCR-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddisjointdataproperties_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDisjointDataProperties-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddisjointdataproperties_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDisjointDataProperties-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddisjointobjectproperties_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDisjointObjectProperties-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddisjointobjectproperties_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDisjointObjectProperties-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2ddisjointunion_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DDisjointUnion-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dirreflexiveproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DIrreflexiveProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d003() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D003");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d004() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D004");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d005() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D005");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d006() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D006");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dkeys_2d007() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DKeys-2D007");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dnegativedatapropertyassertion_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DNegativeDataPropertyAssertion-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dnegativeobjectpropertyassertion_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DNegativeObjectPropertyAssertion-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectpropertychain_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectPropertyChain-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectpropertychain_2dbjp_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectPropertyChain-2DBJP-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectpropertychain_2dbjp_2d003() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectPropertyChain-2DBJP-2D003");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectpropertychain_2dbjp_2d004() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectPropertyChain-2DBJP-2D004");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectqcr_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectQCR-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dobjectqcr_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DObjectQCR-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2drational_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DRational-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2drational_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DRational-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2drational_2d003() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DRational-2D003");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dreflexiveproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DReflexiveProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dselfrestriction_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DSelfRestriction-2D001");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dselfrestriction_2d002() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DSelfRestriction-2D002");
}

#[test]
fn hermit_owl_wg_tests_new_2dfeature_2dtopobjectproperty_2d001() {
    run_wg_case("owl_wg_tests.New-2DFeature-2DTopObjectProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_one_equals_two() {
    run_wg_case("owl_wg_tests.One_equals_two");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2danonymous_2dindividual() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Danonymous-2Dindividual");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2dleftside_2dallvaluesfrom() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Dleftside-2Dallvaluesfrom");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2dleftside_2dmaxcard() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Dleftside-2Dmaxcard");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2doneof() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Doneof");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2dowlreal() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Dowlreal");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2drightside_2dsomevaluesfrom() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Drightside-2Dsomevaluesfrom");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2drightside_2dunionof() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Drightside-2Dunionof");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2dunionof() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Dunionof");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2drules_2dfp_2ddifferentfrom() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Drules-2Dfp-2DdifferentFrom");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2drules_2difp_2daskey() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Drules-2Difp-2Daskey");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2drules_2difp_2ddifferentfrom() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Drules-2Difp-2DdifferentFrom");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dinvalid_2dmincard() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dinvalid-2Dmincard");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dvalid_2doneof() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dvalid-2Doneof");
}

#[test]
fn hermit_owl_wg_tests_owl2_2drl_2dvalid_2drightside_2dallvaluesfrom() {
    run_wg_case("owl_wg_tests.Owl2-2Drl-2Dvalid-2Drightside-2Dallvaluesfrom");
}

#[test]
fn hermit_owl_wg_tests_plus_2dand_2dminus_2d0_2dintegers() {
    run_wg_case("owl_wg_tests.Plus-2Dand-2Dminus-2D0-2Dintegers");
}

#[test]
fn hermit_owl_wg_tests_plus_2dminus_2d0_2dplus_2ddisjointness() {
    run_wg_case("owl_wg_tests.Plus-2Dminus-2D0-2Dplus-2Ddisjointness");
}

#[test]
fn hermit_owl_wg_tests_qualified_2dcardinality_2dboolean() {
    run_wg_case("owl_wg_tests.Qualified-2Dcardinality-2Dboolean");
}

#[test]
fn hermit_owl_wg_tests_qualified_2dcardinality_2drestricted_2dint() {
    run_wg_case("owl_wg_tests.Qualified-2Dcardinality-2Drestricted-2Dint");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dcomplement_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dcomplement-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dintersection_2dinst_2dcomp() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dintersection-2Dinst-2Dcomp");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dintersection_2dinst_2dexpr() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dintersection-2Dinst-2Dexpr");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dintersection_2dterm() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dintersection-2Dterm");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dunion_2dinst_2dcomp() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dunion-2Dinst-2Dcomp");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dbool_2dunion_2dterm() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dbool-2Dunion-2Dterm");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchain_2ddef() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchain-2Ddef");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dasymmetric_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dasymmetric-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dasymmetric_2dterm() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dasymmetric-2Dterm");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dfunctional_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dfunctional-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dinversefunc_2ddata() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dinversefunc-2Ddata");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dinversefunc_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dinversefunc-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dirreflexive_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dirreflexive-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dsymmetric_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dsymmetric-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dchar_2dtransitive_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dchar-2Dtransitive-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dclass_2dnothing_2dext() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dclass-2Dnothing-2Dext");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dclass_2dnothing_2dterm() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dclass-2Dnothing-2Dterm");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dclass_2dnothing_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dclass-2Dnothing-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dclass_2dthing_2dterm() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dclass-2Dthing-2Dterm");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dclass_2dthing_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dclass-2Dthing-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2denum_2dinst_2dincluded() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Denum-2Dinst-2Dincluded");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddifferent_2dirrflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddifferent-2Dirrflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddifferent_2dsameas() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddifferent-2Dsameas");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisclass_2deqclass() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisclass-2Deqclass");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisclass_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisclass-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisclass_2dirrflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisclass-2Dirrflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisprop_2deqprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisprop-2Deqprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisprop_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisprop-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2ddisprop_2dirrflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Ddisprop-2Dirrflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2drflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Drflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dsubclass_2d1() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dsubclass-2D1");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dsubclass_2d2() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dsubclass-2D2");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dsubst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dsubst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dsym() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dsym");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqclass_2dtrans() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqclass-2Dtrans");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2drflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Drflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dsubprop_2d1() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dsubprop-2D1");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dsubprop_2d2() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dsubprop-2D2");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dsubst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dsubst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dsym() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dsym");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2deqprop_2dtrans() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Deqprop-2Dtrans");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2dsameas_2drflxv() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Dsameas-2Drflxv");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2dsameas_2dsubst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Dsameas-2Dsubst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2dsameas_2dsym() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Dsameas-2Dsym");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2deqdis_2dsameas_2dtrans() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Deqdis-2Dsameas-2Dtrans");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dinv_2dinst() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dinv-2Dinst");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dkey_2ddef() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dkey-2Ddef");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dndis_2dalldifferent_2dfw() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dndis-2Dalldifferent-2Dfw");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dndis_2dalldifferent_2dfw_2ddistinctmembers() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dndis-2Dalldifferent-2Dfw-2Ddistinctmembers");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dndis_2dalldisjointclasses_2dfw() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dndis-2Dalldisjointclasses-2Dfw");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dndis_2dalldisjointproperties_2dfw() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dndis-2Dalldisjointproperties-2Dfw");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dnpa_2ddat_2dfw() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dnpa-2Ddat-2Dfw");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dnpa_2dind_2dfw() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dnpa-2Dind-2Dfw");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dbackwardcompatiblewith_2dtype_2dannot() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dbackwardcompatiblewith-2Dtype-2Dannot");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dcomment_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dcomment-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2ddeprecated_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Ddeprecated-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dincompatiblewith_2dtype_2dannot() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dincompatiblewith-2Dtype-2Dannot");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2disdefinedby_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Disdefinedby-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dlabel_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dlabel-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dpriorversion_2dtype_2dannot() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dpriorversion-2Dtype-2Dannot");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dseealso_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dseealso-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2dprop_2dversioninfo_2dtype() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Dprop-2Dversioninfo-2Dtype");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2ddomain_2dcond() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Ddomain-2Dcond");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2drange_2dcond() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Drange-2Dcond");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2dsubclass_2dcond() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Dsubclass-2Dcond");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2dsubclass_2dtrans() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Dsubclass-2Dtrans");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2dsubprop_2dcond() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Dsubprop-2Dcond");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfs_2dsubprop_2dtrans() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfs-2Dsubprop-2Dtrans");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfsext_2ddomain_2dsubprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfsext-2Ddomain-2Dsubprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfsext_2ddomain_2dsuperclass() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfsext-2Ddomain-2Dsuperclass");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfsext_2drange_2dsubprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfsext-2Drange-2Dsubprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drdfsext_2drange_2dsuperclass() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drdfsext-2Drange-2Dsuperclass");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dallvalues_2dcmp_2dclass() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dallvalues-2Dcmp-2Dclass");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dallvalues_2dcmp_2dprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dallvalues-2Dcmp-2Dprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dallvalues_2dinst_2dobj() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dallvalues-2Dinst-2Dobj");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dhasvalue_2dcmp_2dprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dhasvalue-2Dcmp-2Dprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dhasvalue_2dinst_2dobj() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dhasvalue-2Dinst-2Dobj");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dhasvalue_2dinst_2dsubj() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dhasvalue-2Dinst-2Dsubj");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dmaxcard_2dinst_2dobj_2done() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dmaxcard-2Dinst-2Dobj-2Done");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dmaxcard_2dinst_2dobj_2dzero() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dmaxcard-2Dinst-2Dobj-2Dzero");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dmaxqcr_2dinst_2dobj_2done() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dmaxqcr-2Dinst-2Dobj-2Done");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dmaxqcr_2dinst_2dobj_2dzero() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dmaxqcr-2Dinst-2Dobj-2Dzero");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dsomevalues_2dcmp_2dclass() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dsomevalues-2Dcmp-2Dclass");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dsomevalues_2dcmp_2dprop() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dsomevalues-2Dcmp-2Dprop");
}

#[test]
fn hermit_owl_wg_tests_rdfbased_2dsem_2drestrict_2dsomevalues_2dinst_2dsubj() {
    run_wg_case("owl_wg_tests.Rdfbased-2Dsem-2Drestrict-2Dsomevalues-2Dinst-2Dsubj");
}

#[test]
fn hermit_owl_wg_tests_somevaluesfrom2bnode() {
    run_wg_case("owl_wg_tests.Somevaluesfrom2bnode");
}

#[test]
fn hermit_owl_wg_tests_string_2dinteger_2dclash() {
    run_wg_case("owl_wg_tests.String-2Dinteger-2Dclash");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dalldifferent_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DAllDifferent-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dannotationproperty_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DAnnotationProperty-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dannotationproperty_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DAnnotationProperty-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dannotationproperty_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DAnnotationProperty-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dfunctionalproperty_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DFunctionalProperty-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dfunctionalproperty_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DFunctionalProperty-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_5_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.5-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_5_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.5-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_6_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.6-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_6_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.6-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_6_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.6-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di4_6_2d005_2ddirect() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI4.6-2D005-2DDirect");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_1_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.1-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_1_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.1-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_2_2d011() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.2-2D011");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_21_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.21-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_24_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.24-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_24_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.24-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_24_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.24-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_24_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.24-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_26_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.26-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_3_2d011() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.3-2D011");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_5_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.5-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_5_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.5-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_5_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.5-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_5_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.5-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_5_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.5-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d011() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D011");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d016() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D016");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di5_8_2d017() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI5.8-2D017");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2di6_1_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DI6.1-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dinversefunctionalproperty_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DInverseFunctionalProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dinversefunctionalproperty_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DInverseFunctionalProperty-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dinversefunctionalproperty_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DInverseFunctionalProperty-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dnothing_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DNothing-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dnothing_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DNothing-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dontology_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DOntology-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dontology_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DOntology-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2drestriction_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DRestriction-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2drestriction_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DRestriction-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2drestriction_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DRestriction-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2drestriction_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DRestriction-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2drestriction_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DRestriction-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsymmetricproperty_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DSymmetricProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsymmetricproperty_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DSymmetricProperty-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsymmetricproperty_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DSymmetricProperty-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dthing_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DThing-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dthing_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DThing-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dthing_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DThing-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dtransitiveproperty_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DTransitiveProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dtransitiveproperty_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DTransitiveProperty-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dallvaluesfrom_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DallValuesFrom-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dallvaluesfrom_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DallValuesFrom-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dbackwardcompatiblewith_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DbackwardCompatibleWith-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dbackwardcompatiblewith_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DbackwardCompatibleWith-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcardinality_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dcardinality-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcardinality_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dcardinality-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcardinality_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dcardinality-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcardinality_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dcardinality-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcardinality_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dcardinality-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dcomplementof_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DcomplementOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d011() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D011");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d012() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D012");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d013() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D013");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d014() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D014");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d015() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D015");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d016() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D016");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d017() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D017");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d018() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D018");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d019() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D019");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d020() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D020");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d021() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D021");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d022() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D022");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d023() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D023");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d024() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D024");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d025() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D025");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d026() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D026");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d027() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D027");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d028() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D028");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d029() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D029");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d030() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D030");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d031() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D031");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d032() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D032");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d033() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D033");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d034() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D034");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d035() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D035");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d040() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D040");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d101() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D101");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d102() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D102");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d103() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D103");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d104() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D104");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d105() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D105");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d106() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D106");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d107() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D107");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d108() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D108");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d109() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D109");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d110() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D110");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d111() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D111");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d201() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D201");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d205() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D205");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d207() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D207");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d208() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D208");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d209() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D209");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d501() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D501");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d502() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D502");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d503() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D503");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d504() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D504");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d601() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D601");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d602() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D602");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d603() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D603");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d604() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D604");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d605() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D605");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d606() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D606");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d608() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D608");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d609() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D609");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d610() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D610");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d611() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D611");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d612() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D612");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d613() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D613");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d614() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D614");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d615() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D615");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d616() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D616");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d617() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D617");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d623() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D623");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d624() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D624");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d625() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D625");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d626() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D626");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d627() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D627");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d628() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D628");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d629() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D629");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d630() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D630");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d631() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D631");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d632() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D632");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d633() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D633");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d634() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D634");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d641() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D641");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d642() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D642");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d643() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D643");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d644() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D644");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d646() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D646");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d650() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D650");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d661() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D661");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d665() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D665");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d667() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D667");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d901() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D901");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d902() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D902");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d904() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D904");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d905() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D905");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d907() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D907");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d908() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D908");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddescription_2dlogic_2d910() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Ddescription-2Dlogic-2D910");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddifferentfrom_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdifferentFrom-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddifferentfrom_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdifferentFrom-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddisjointwith_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdisjointWith-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2ddistinctmembers_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DdistinctMembers-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d005() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D005");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d006() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D006");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d008_2ddirect() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D008-2DDirect");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentclass_2d009() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentClass-2D009");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentproperty_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentProperty-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentproperty_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentProperty-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentproperty_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentProperty-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dequivalentproperty_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DequivalentProperty-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dimports_2d007() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dimports-2D007");
}

#[test]
fn hermit_owl_wg_tests_webont_2dimports_2d007_2dimport_2dimports007() {
    run_wg_case("owl_wg_tests.WebOnt-2Dimports-2D007-2Dimport-2Dimports007");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dimports_2d008() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dimports-2D008");
}

#[test]
fn hermit_owl_wg_tests_webont_2dimports_2d008_2dimport_2dimports008() {
    run_wg_case("owl_wg_tests.WebOnt-2Dimports-2D008-2Dimport-2Dimports008");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dimports_2d010() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dimports-2D010");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dimports_2d011() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dimports-2D011");
}

#[test]
fn hermit_owl_wg_tests_webont_2dimports_2d014_2dimport_2dimports014() {
    run_wg_case("owl_wg_tests.WebOnt-2Dimports-2D014-2Dimport-2Dimports014");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dintersectionof_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DintersectionOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dinverseof_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DinverseOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmaxcardinality_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DmaxCardinality-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d102() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D102");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d103() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D103");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d202() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D202");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d203() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D203");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d204() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D204");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d301() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D301");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d302() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D302");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d302_2ddirect() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D302-2DDirect");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dmiscellaneous_2d303() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2Dmiscellaneous-2D303");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2doneof_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DoneOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2doneof_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DoneOf-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2doneof_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DoneOf-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2doneof_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DoneOf-2D004");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsameas_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DsameAs-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsomevaluesfrom_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DsomeValuesFrom-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsomevaluesfrom_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DsomeValuesFrom-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dsomevaluesfrom_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DsomeValuesFrom-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dunionof_2d001() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DunionOf-2D001");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dunionof_2d002() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DunionOf-2D002");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dunionof_2d003() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DunionOf-2D003");
}

#[test]
fn hermit_owl_wg_tests_testcase_3awebont_2dunionof_2d004() {
    run_wg_case("owl_wg_tests.TestCase-3AWebOnt-2DunionOf-2D004");
}
