[package]
name = "ontologos-rdfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "RDFS reasoning engine for OntoLogos"
documentation = "https://docs.rs/ontologos-rdfs"
publish = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
ontologos-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ontologos-parser = { workspace = true }
