[package]
name = "ontologos-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "OWL/RDF parsers for OntoLogos"
readme = "README.md"
publish = true


[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
ontologos-core = { workspace = true }
horned-owl = { workspace = true }
oxrdfio = "0.2"
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
horned-owl = { workspace = true, features = ["remote"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[dev-dependencies]
ontologos-profile = { workspace = true }
criterion = "0.5"

[[bench]]
name = "load"
harness = false

