[package]
name = "ontologos-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "OWL/RDF parsers for OntoLogos"
publish = true

[dependencies]
ontologos-core = { workspace = true }
horned-owl = { workspace = true }
oxrdfio = "0.2"
thiserror = { workspace = true }

[dev-dependencies]
ontologos-profile = { workspace = true }
