[package]
name = "ontologos-dotnet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Native library for OntoLogos .NET bindings"
publish = false

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
name = "ontologos_dotnet"

[dependencies]
ontologos-ffi = { path = "../ontologos-ffi" }
